name=IskakINO_ArduFast
version=1.0.1
author=Iskak Fatoni
maintainer=Iskak Fatoni <iskakfatoni@gmail.com>
sentence=Ultra-fast direct-register I/O and non-blocking multitasking framework for Arduino.
paragraph=A lightweight framework optimized for AVR, ESP8266, and ESP32. FastPin<P> uses true direct register access on AVR/ESP32/ESP8266, with automated analog normalization/mapping and a simple non-blocking task scheduler.
category=Device Control
url=https://github.com/iskakfatoni/IskakINO_ArduFast
architectures=*
includes=IskakINO_ArduFast.h
